signature = [
    160,
    107,
    15,
    177,
    151,
    156,
    58,
    82,
    109,
    121,
    122,
    1,
    156,
    120,
    249,
    105,
    160,
    157,
    153,
    115,
    85,
    61,
    62,
    53,
    61,
    121,
    164,
    162,
    144,
    65,
    164,
    16,
    7,
    146,
    204,
    206,
    16,
    130,
    31,
    50,
    128,
    70,
    163,
    106,
    2,
    74,
    47,
    71,
    54,
    108,
    45,
    240,
    204,
    98,
    115,
    68,
    210,
    7,
    10,
    169,
    135,
    200,
    224,
    71,
]
total_len = "47"

[card_number]
field_type = "1"
tdd_field_id = "AL"

[card_number.pattern]
_is_some = "1"

[card_number.pattern._value]
len = "11"
storage = [
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "48",
    "49",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
]

[card_number.value]
_is_some = "0"
_value = "0"

[card_number.inequality]
_is_some = "0"
_value = "0"

[data.fields]
len = "2"

[[data.fields.storage]]
id = "AL"

[data.fields.storage.data]
len = "11"
storage = [
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "48",
    "49",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
]

[[data.fields.storage]]
id = "AI"

[data.fields.storage.data]
len = "8"
storage = [
    "51",
    "48",
    "49",
    "49",
    "50",
    "48",
    "49",
    "57",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
]

[data.header]
ca_id = "FR00"
cert_id = "0001"
country_id = "FR"
doc_type_id = "A5"
perimeter_id = "1"
version = "3"

[data.header.emit_date]
day = "06"
month = "06"
year = "2179"

[data.header.sign_date]
day = "18"
month = "06"
year = "2017"
